name: Build and deploy Node.js app to Azure Web App - BackApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: |
          cd back
          npm install

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_10E7AF5CB53142AF88343158E7C5BFC3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_307DE4DE173B41DEA16867FD6BAE1388 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_622BA9DC3B874F1D884ECF9319877C93 }}

      - name: Configure Azure DevOps organization
        run: |
          az webapp config appsettings set \
            --resource-group "AppSilver" \
            --name "BackApp" \
            --settings AZURE_DEVOPS_ORGANIZATION=fabricadev

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "BackApp"
          slot-name: "Production"
          package: ./back
